apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: joomla
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: rootpassword
  MARIADB_DATABASE: joomla
  MARIADB_USER: joomla
  MARIADB_PASSWORD: joomlapassword
