apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joomla
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/tabbi/joomla-gitops.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: joomla

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
